# Generated by Django 5.0.6 on 2024-05-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_cartitem_cart_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
